### ISSUE TITLE
DongShanPi One schematics

### ISSUE THREAD

**Issue by x893** [DongshanPI/Dongshanpi-Docs#10]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

Hello,
can you help me with schematics for module **DongShanPi One**

[http://linux-chenxing.org/infinity2/dongshanpione/board_red_scaled.jpg](http://linux-chenxing.org/infinity2/dongshanpione/board_red_scaled.jpg)

Thanks

### Use Cases

May be help to others

### Screenshots / Mockups

[http://linux-chenxing.org/infinity2/dongshanpione/board_red_scaled.jpg](http://linux-chenxing.org/infinity2/dongshanpione/board_red_scaled.jpg)

**Comment by DongshanPI** [comment]
DShanPi ONE SCH  PDF  Download Link https://cowtransfer.com/s/9b745ce262544c

**Comment by x893** [comment]
Thank you !
